### ISSUE TITLE
Error whilst importing Livestreamer?

### ISSUE THREAD

**Issue by 1ben99** [ohyou/twitch-viewer#17]
Hi when I run this command to start the live stream I get this error: 

PS C:\Users\Mars> python C:\Python27\StreamBot\streambot.py koorija
Obtaining the channel...
Obtained the channel
Preparing the processes...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\python27\Scripts\livestreamer.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\livestreamer_cli\main.py", line 14, in <module>
    from livestreamer import (Livestreamer, StreamError, PluginError,
ImportError: cannot import name Livestreamer
An error has occurred while trying to get the stream data. Is the channel online? Is the channel name correct?

Any help is appreciated thanks!

**Comment by ohyou** [comment]
I'm closing this issue because the project is currently not maintained and it will unlikely to be resolved.  
For more, please read this: https://github.com/ohyou/twitch-viewer/blob/master/README.md#project-state
