### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by nimiane** [ohyou/twitch-viewer#20]
Unsure what's going on here or how to fix it.
```
python C:\view\twitch-viewer.py test
Obtaining the channel...
Obtained the channel
Preparing the processes...
Traceback (most recent call last):
  File "C:\view\twitch-viewer.py", line 112, in <module>
    prepare_processes()
  File "C:\view\twitch-viewer.py", line 100, in prepare_processes
    "url": get_url(), "proxy": {
  File "C:\view\twitch-viewer.py", line 64, in get_url
    url = json.loads(response)['streams']['audio']['url']
  File "C:\Users\Me\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by nimiane** [comment]
Had to download a previous version of python to get it to work. Won't work in 3.
