### ISSUE TITLE
ProxySchemeUnknown: Not supported proxy scheme

### ISSUE THREAD

**Issue by rasurbrand** [ohyou/twitch-viewer#46]
Hey,

I got some errors with reading my proxylist.txt.

My list looks like this
ip:port
ip:port

But when I run the script, it looses the port while running..
Has anyone an idea? 

Obtaining the channel...
Obtained the channel
Preparing the processes...
. . . . . . . . . . . . . . . . . . . . .
Prepared the processes
Booting up the processes...
Process Process-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 232, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "C:\python27\twitch-viewer.py", line 80, in open_url
    response = s.head(url, proxies=proxy)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 568, in head
    return self.request('HEAD', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 199, in proxy_manager_for
    **proxy_kwargs)
  File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 450, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 401, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
ProxySchemeUnknown: Not supported proxy scheme 37.59.248.191

**Comment by rasurbrand** [comment]
Got it. Have do enable the Admin Account on win10 Pro and run it from this account.
Thx to everyone.

**Comment by s4magier** [comment]
Is this bot working for you? Does Twitch count the viewers? @schroedaa

**Comment by rasurbrand** [comment]
Yes, it works fine

**Comment by s4magier** [comment]
Did you change anything of the original code? Twitch doesnt count requests as viewers anymore.

**Comment by mufin695** [comment]
> Did you change anything of the original code? Twitch doesnt count requests as viewers anymore.

no way the original code is working. 



> Yes, it works fine
> […](#)
> Am 03.01.2019 um 12:03 schrieb s4magier ***@***.***>: Is this bot working for you? Does Twitch count the viewers? @schroedaa — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

If you do have it working please share :)

**Comment by rasurbrand** [comment]
The original code from @justinharkey.
For all the others: you have to active the admin account on win 10 pro and run the script from there. "As Admin". Works fine for me. Thanks to @virtuoz75 for his support.

**Comment by s4magier** [comment]
I mean it is running @schroedaa but its not counting viewers for me

**Comment by rasurbrand** [comment]
Yes, it tools a while, about~10min. 
May check you proxy list with „proxy switcher“ to see which server are possible dead.

**Comment by s4magier** [comment]
@schroedaa i have implemented a proxy check which deletes dead proxies. Still my viewers dont count. Which settings do you use for the sleep timeouts?

**Comment by rasurbrand** [comment]
20ms

**Comment by GL1TCH1337** [comment]
i have this problem and i'm using linux. anyone have an idea?
