### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by 0piero** [ohyou/twitch-viewer#56]
An error has occurred while trying to use livestreamer package. Is it installed? Do you have Python in your PATH variable?    
Traceback (most recent call last):                                                                                            
  File "twitch-viewer.py", line 115, in <module>                                                                              
    prepare_processes()                                                                                                       
  File "twitch-viewer.py", line 103, in prepare_processes                                                                     
    "url": get_url(), "proxy": {                                                                                              
  File "twitch-viewer.py", line 67, in get_url                                                                                
    url = json.loads(response)['streams']['worst']['url']                                                                     
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by white-hackers** [comment]
Traceback (most recent call last):
  File "twitch-viewer.py", line 100, in <module>
    prepare_processes()
  File "twitch-viewer.py", line 88, in prepare_processes
    "url": get_url(), "proxy": {
  File "twitch-viewer.py", line 52, in get_url
    url = json.loads(response)['streams']['worst']['url']
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by white-hackers** [comment]
+
