### ISSUE TITLE
I get this error when using python3 TVB.py lejobuildlive: An error has occurred while trying to use livestreamer package. Is it installed? Do you have Python in your PATH variable?

### ISSUE THREAD

**Issue by Lejobuild** [ohyou/twitch-viewer#62]

**Comment by JJoshyyy** [comment]
@Lejobuild try running the following:
pip install livestreamer
then try again

**Comment by Petros-Tsimvris** [comment]
I have the same issue too @JJoshyyy , pip is already installed.
`Requirement already satisfied: livestreamer in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.12.2)
Requirement already satisfied: requests<3.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from livestreamer) (2.28.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (2.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (2022.12.7)
`

**Comment by Petros-Tsimvris** [comment]
An error has occurred while trying to use livestreamer package. Is it installed? Do you have Python in your PATH variable?
Traceback (most recent call last):
  File "/Users/user/Desktop/Development/twitch-viewer/twitch-viewer.py", line 48, in get_url
    url = json.loads(response)['streams']['audio_only']['url']
                     ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

**Comment by JJoshyyy** [comment]
> I have the same issue too @JJoshyyy , pip is already installed. `Requirement already satisfied: livestreamer in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.12.2) Requirement already satisfied: requests<3.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from livestreamer) (2.28.1) Requirement already satisfied: charset-normalizer<3,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (2.1.1) Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (2.8) Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (1.26.5) Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests<3.0,>=1.0->livestreamer) (2022.12.7) `

That means nothing, its just saying that the apps are already installed



> An error has occurred while trying to use livestreamer package. Is it installed? Do you have Python in your PATH variable? Traceback (most recent call last): File "/Users/user/Desktop/Development/twitch-viewer/twitch-viewer.py", line 48, in get_url url = json.loads(response)['streams']['audio_only']['url'] ^^^^^^^^ UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

No clue, try lookuing elsewhere

**Comment by JJoshyyy** [comment]
> 

Do the exact thing as i said above bro. pip install livestreamer

**Comment by Petros-Tsimvris** [comment]
i install livestreamer again, the problem remains the same

**Comment by Petros-Tsimvris** [comment]
maybe its a problem caused because im running it from a Mac?

**Comment by JJoshyyy** [comment]
> maybe its a problem caused because im running it from a Mac?

Most likely in that case. Try setting up a vm running windows
